Traceback (most recent call last):
  File "sniper.py", line 104, in <module>
    bot.run(token, bot=False)
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 637, in run
    _cleanup_loop(loop)
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 92, in _cleanup_loop
    _cancel_tasks(loop)
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 77, in _cancel_tasks
    loop.run_until_complete(asyncio.gather(*tasks, return_exceptions=True))
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 585, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
